/**
 * Modoki API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.1.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ModokiApi) {
      root.ModokiApi = {};
    }
    root.ModokiApi.GoaContainerListEach = factory(root.ModokiApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GoaContainerListEach model module.
   * @module model/GoaContainerListEach
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>GoaContainerListEach</code>.
   * GoaContainerListEach media type (default view)
   * @alias module:model/GoaContainerListEach
   * @class
   * @param command {String} Command to run when starting the container
   * @param created {Date} The time the container was created
   * @param id {Number} ID
   * @param image {String} The name of the image to use when creating the container
   * @param imageID {String} The container's image ID
   * @param name {String} Assign the specified name to the container. Must match /?[a-zA-Z0-9_-]+.
   * @param status {module:model/GoaContainerListEach.StatusEnum} 
   * @param volumes {Array.<String>} Paths to mount volumes in
   */
  var exports = function(command, created, id, image, imageID, name, status, volumes) {
    var _this = this;

    _this['command'] = command;
    _this['created'] = created;
    _this['id'] = id;
    _this['image'] = image;
    _this['imageID'] = imageID;
    _this['name'] = name;
    _this['status'] = status;
    _this['volumes'] = volumes;
  };

  /**
   * Constructs a <code>GoaContainerListEach</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GoaContainerListEach} obj Optional instance to populate.
   * @return {module:model/GoaContainerListEach} The populated <code>GoaContainerListEach</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('command')) {
        obj['command'] = ApiClient.convertToType(data['command'], 'String');
      }
      if (data.hasOwnProperty('created')) {
        obj['created'] = ApiClient.convertToType(data['created'], 'Date');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('image')) {
        obj['image'] = ApiClient.convertToType(data['image'], 'String');
      }
      if (data.hasOwnProperty('imageID')) {
        obj['imageID'] = ApiClient.convertToType(data['imageID'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('volumes')) {
        obj['volumes'] = ApiClient.convertToType(data['volumes'], ['String']);
      }
    }
    return obj;
  }

  /**
   * Command to run when starting the container
   * @member {String} command
   */
  exports.prototype['command'] = undefined;
  /**
   * The time the container was created
   * @member {Date} created
   */
  exports.prototype['created'] = undefined;
  /**
   * ID
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * The name of the image to use when creating the container
   * @member {String} image
   */
  exports.prototype['image'] = undefined;
  /**
   * The container's image ID
   * @member {String} imageID
   */
  exports.prototype['imageID'] = undefined;
  /**
   * Assign the specified name to the container. Must match /?[a-zA-Z0-9_-]+.
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {module:model/GoaContainerListEach.StatusEnum} status
   */
  exports.prototype['status'] = undefined;
  /**
   * Paths to mount volumes in
   * @member {Array.<String>} volumes
   */
  exports.prototype['volumes'] = undefined;


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "Creating"
     * @const
     */
    "Creating": "Creating",
    /**
     * value: "Created"
     * @const
     */
    "Created": "Created",
    /**
     * value: "Running"
     * @const
     */
    "Running": "Running",
    /**
     * value: "Stopped"
     * @const
     */
    "Stopped": "Stopped",
    /**
     * value: "Error"
     * @const
     */
    "Error": "Error"  };


  return exports;
}));


