/**
 * Modoki API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.1.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ModokiApi) {
      root.ModokiApi = {};
    }
    root.ModokiApi.GoaUserDefaultshell = factory(root.ModokiApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GoaUserDefaultshell model module.
   * @module model/GoaUserDefaultshell
   * @version 1.0
   */

  /**
   * Constructs a new <code>GoaUserDefaultshell</code>.
   * GoaUserDefaultshell media type (default view)
   * @alias module:model/GoaUserDefaultshell
   * @class
   * @param defaultShell {String} 
   */
  var exports = function(defaultShell) {
    var _this = this;

    _this['defaultShell'] = defaultShell;
  };

  /**
   * Constructs a <code>GoaUserDefaultshell</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GoaUserDefaultshell} obj Optional instance to populate.
   * @return {module:model/GoaUserDefaultshell} The populated <code>GoaUserDefaultshell</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('defaultShell')) {
        obj['defaultShell'] = ApiClient.convertToType(data['defaultShell'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} defaultShell
   */
  exports.prototype['defaultShell'] = undefined;



  return exports;
}));


