/**
 * Modoki API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.1.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ModokiApiDocumentation);
  }
}(this, function(expect, ModokiApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ModokiApiDocumentation.GoaContainerInspectRawState();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GoaContainerInspectRawState', function() {
    it('should create an instance of GoaContainerInspectRawState', function() {
      // uncomment below and update the code to test GoaContainerInspectRawState
      //var instance = new ModokiApiDocumentation.GoaContainerInspectRawState();
      //expect(instance).to.be.a(ModokiApiDocumentation.GoaContainerInspectRawState);
    });

    it('should have the property dead (base name: "dead")', function() {
      // uncomment below and update the code to test the property dead
      //var instance = new ModokiApiDocumentation.GoaContainerInspectRawState();
      //expect(instance).to.be();
    });

    it('should have the property exitCode (base name: "exitCode")', function() {
      // uncomment below and update the code to test the property exitCode
      //var instance = new ModokiApiDocumentation.GoaContainerInspectRawState();
      //expect(instance).to.be();
    });

    it('should have the property finishedAt (base name: "finishedAt")', function() {
      // uncomment below and update the code to test the property finishedAt
      //var instance = new ModokiApiDocumentation.GoaContainerInspectRawState();
      //expect(instance).to.be();
    });

    it('should have the property oomKilled (base name: "oomKilled")', function() {
      // uncomment below and update the code to test the property oomKilled
      //var instance = new ModokiApiDocumentation.GoaContainerInspectRawState();
      //expect(instance).to.be();
    });

    it('should have the property paused (base name: "paused")', function() {
      // uncomment below and update the code to test the property paused
      //var instance = new ModokiApiDocumentation.GoaContainerInspectRawState();
      //expect(instance).to.be();
    });

    it('should have the property pid (base name: "pid")', function() {
      // uncomment below and update the code to test the property pid
      //var instance = new ModokiApiDocumentation.GoaContainerInspectRawState();
      //expect(instance).to.be();
    });

    it('should have the property restarting (base name: "restarting")', function() {
      // uncomment below and update the code to test the property restarting
      //var instance = new ModokiApiDocumentation.GoaContainerInspectRawState();
      //expect(instance).to.be();
    });

    it('should have the property running (base name: "running")', function() {
      // uncomment below and update the code to test the property running
      //var instance = new ModokiApiDocumentation.GoaContainerInspectRawState();
      //expect(instance).to.be();
    });

    it('should have the property startedAt (base name: "startedAt")', function() {
      // uncomment below and update the code to test the property startedAt
      //var instance = new ModokiApiDocumentation.GoaContainerInspectRawState();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new ModokiApiDocumentation.GoaContainerInspectRawState();
      //expect(instance).to.be();
    });

  });

}));
